#!/bin/bash

CURRENT_DIR=$(pwd)

DNSMASQ_DIR=$CURRENT_DIR/servidor-base/dnsmasq
TRAEFIK_DIR=$CURRENT_DIR/servidor-base/traefik

PLATAFORMA_DIR=$CURRENT_DIR/plataforma-instituto

install_server() {
  echo "Instalando servidor base"
  # linkear las variables de entorno globales
  if [[ ! -d "$DNSMASQ_DIR/.env" ]]; then
    ln -s "$CURRENT_DIR/.global.env" "$DNSMASQ_DIR/.env" &>/dev/null
  fi

  if [[ ! -d "$TRAEFIK_DIR/.env" ]]; then
    ln -s "$CURRENT_DIR/.global.env" "$TRAEFIK_DIR/.env" &>/dev/null
  fi

  # generar nuevos certificados tls
  if [[ ! -d "$TRAEFIK_DIR/certs" ]]; then
      mkdir -p "$TRAEFIK_DIR/certs"
  fi

  if [[ ! ( -f "$TRAEFIK_DIR/certs/local.key" && -f "$TRAEFIK_DIR/certs/local.crt" ) ]]; then
    echo "Generando certificados SSL..."
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout "$TRAEFIK_DIR/certs/local.key" -out "$TRAEFIK_DIR/certs/local.crt" \
      -subj "/CN=*.$HOST" &>/dev/null
  fi
}

install_plataforma() {
  echo "Instalando plataforma Moodle"

  if [[ ! -d "$PLATAFORMA_DIR/.env" ]]; then
    ln -s "$CURRENT_DIR/.global.env" "$PLATAFORMA_DIR/.env" &>/dev/null
  fi

  if [[ ! -d "$PLATAFORMA_DIR/moodledata" ]]; then
      mkdir -p "$PLATAFORMA_DIR/moodledata"
      chmod 777 -R "$PLATAFORMA_DIR/moodledata"
  fi

  if [[ ! -d "$PLATAFORMA_DIR/db-data" ]]; then
      mkdir -p "$PLATAFORMA_DIR/db-data"
  fi

  echo "Creando imagen de mooodle"
  docker compose --project-directory "$PLATAFORMA_DIR/plataforma-instituto" build &>/dev/null
}

main() {
  if [[ ! -f .global.env ]]; then
      echo "No se encontro archivo de variables de entorno globales '.global.env'"
      exit 1
  fi

  # obtener variables de entorno globales
  while IFS='=' read -r key value; do
    [[ -z "$key" || "$key" =~ ^# ]] && continue
    value="${value%\"}"; value="${value#\"}"
    value="${value%\'}"; value="${value#\'}"
    export "$key=$value"
  done < .global.env

  install_server
  install_plataforma
}

main $@
